# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'WRWW' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WRWW
  pod 'Alamofire'
  pod 'FBSDKCoreKit'
  pod 'FBSDKShareKit'
  pod 'FBSDKLoginKit'
  pod 'LoopBack', :git => 'https://github.com/strongloop/loopback-sdk-ios.git'
  pod 'SlackTextViewController'
  pod 'TTTAttributedLabel'
  pod 'Locksmith'
  pod 'CameraManager', '~> 2.2'
  pod 'DropDown'
  pod 'CollectionViewWaterfallLayout'
  pod 'SCLAlertView'
  pod 'OpenCV'
end
